# Generated by Django 2.2.4 on 2019-09-02 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoredUpload',
            fields=[
                ('upload_id', models.CharField(max_length=22, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(22)])),
                ('file_path', models.CharField(max_length=2048, null=True, unique=True)),
                ('uploaded', models.DateTimeField()),
                ('stored', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryUpload',
            fields=[
                ('upload_id', models.CharField(max_length=22, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(22)])),
                ('file_id', models.CharField(max_length=22, validators=[django.core.validators.MinLengthValidator(22)])),
                ('file_path', models.CharField(max_length=2048, null=True, unique=True)),
                ('url', models.URLField(null=True)),
                ('upload_name', models.CharField(max_length=512)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('upload_type', models.CharField(choices=[('F', 'Uploaded file data'), ('U', 'Remote file URL')], max_length=1)),
            ],
        ),
    ]
