# Generated by Django 2.2.4 on 2020-03-08 01:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('django_drf_filepond', '0001_initial'), ('django_drf_filepond', '0002_add_upload_dir'), ('django_drf_filepond', '0003_add_storedupload'), ('django_drf_filepond', '0004_auto_20190710_0334'), ('django_drf_filepond', '0005_auto_20190712_2003'), ('django_drf_filepond', '0006_auto_20190720_0214'), ('django_drf_filepond', '0007_auto_20190802_0333'), ('django_drf_filepond', '0004_auto_20190802_0508'), ('django_drf_filepond', '0008_merge_20190818_2358'), ('django_drf_filepond', '0009_auto_20190819_0041'), ('django_drf_filepond', '0010_auto_20190827_1448'), ('django_drf_filepond', '0011_auto_20190902_0123'), ('django_drf_filepond', '0012_auto_20200307_2251')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoredUpload',
            fields=[
                ('upload_id', models.CharField(max_length=22, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(22)])),
                ('file_path', models.CharField(max_length=2048, null=True)),
                ('uploaded', models.DateTimeField()),
                ('stored', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryUpload',
            fields=[
                ('upload_id', models.CharField(max_length=22, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(22)])),
                ('upload_name', models.CharField(max_length=512)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('upload_type', models.CharField(choices=[('F', 'Uploaded file data'), ('U', 'Remote file URL')], max_length=1)),
                ('file_id', models.CharField(max_length=22, validators=[django.core.validators.MinLengthValidator(22)])),
                ('url', models.URLField(null=True)),
                ('file_path', models.CharField(max_length=2048, null=True)),
            ],
        ),
    ]
