# Generated by Django 2.2.4 on 2019-08-02 03:08

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django_drf_filepond.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_drf_filepond', '0003_add_storedupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryupload',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='temporaryupload',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Casper\\Desktop\\django-drf-filepond\\filepond_uploads'), upload_to=django_drf_filepond.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='temporaryupload',
            name='file_id',
            field=models.CharField(max_length=22, validators=[django.core.validators.MinLengthValidator(22)]),
        ),
    ]
