# Generated by Django 2.1.10 on 2019-07-12 18:03

import django.core.files.storage
from django.db import migrations, models
import django_drf_filepond.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_drf_filepond', '0004_auto_20190710_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryupload',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\ConnectHouses\\ConnectHouses\\media\\fp_temp'), upload_to=django_drf_filepond.models.get_upload_path),
        ),
    ]
