# Generated by Django 2.1.10 on 2019-08-02 01:33

import django.core.files.storage
from django.db import migrations, models
import django_drf_filepond.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_drf_filepond', '0006_auto_20190720_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryupload',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='temporaryupload',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='//cdn.connecthouses.com/media/fp_temp'), upload_to=django_drf_filepond.models.get_upload_path),
        ),
    ]
