# Generated by Django 2.1.10 on 2019-08-18 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_drf_filepond', '0007_auto_20190802_0333'),
        ('django_drf_filepond', '0004_auto_20190802_0508'),
    ]

    operations = [
    ]
