# Generated by Django 2.1.10 on 2019-08-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_drf_filepond', '0008_merge_20190818_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryupload',
            name='file',
        ),
        migrations.AddField(
            model_name='temporaryupload',
            name='file_path',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
