# Generated by Django 2.2.4 on 2019-08-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_drf_filepond', '0009_auto_20190819_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryupload',
            name='file_path',
            field=models.CharField(default='', max_length=2048, null=True),
        ),
    ]
