# Generated by Django 2.1.10 on 2019-09-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_drf_filepond', '0010_auto_20190827_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedupload',
            name='file_path',
            field=models.CharField(max_length=2048, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='temporaryupload',
            name='file_path',
            field=models.CharField(max_length=2048, null=True, unique=True),
        ),
    ]
