# Generated by Django 2.2.4 on 2020-03-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_drf_filepond', '0011_auto_20190902_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedupload',
            name='file_path',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='temporaryupload',
            name='file_path',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
