# Generated by Django 2.2.4 on 2020-02-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_drf_filepond', '0012_auto_20200209_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedupload',
            name='file_path',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
