# Generated by Django 2.2.4 on 2020-02-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_drf_filepond', '0013_auto_20200209_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedupload',
            name='file_path',
            field=models.CharField(max_length=2048, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='temporaryupload',
            name='file_path',
            field=models.CharField(max_length=2048, null=True, unique=True),
        ),
    ]
